#!/bin/bash

#pip3 install --force-reinstall -v "python-telegram-bot==13.5"


TOKEN="5981434873:AAE1e260sk_8Xu5Gy9N93zodag9WBHuaxOM"
CHAT_ID="-1001876237467"
LOG_FILE="/var/log/syslog"

#70521


# Inicia el bucle infinito para monitorear el archivo de registro de DHCP
tail -n0 -f "$LOG_FILE" | while read LINE; do

  # Busca los mensajes relevantes usando grep
  if echo "$LINE" | grep -q "dhcpd:"; then

    # Envía el mensaje a través de la API de Telegram usando curl
    curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
      -d chat_id="$CHAT_ID" \
      -d text="$LINE"

  fi
done
